# Makefile for Writing Make Files Example
 
# *****************************************************
# Variables to control Makefile operation
 
CC = g++
#CFLAGS = -Wall -g
 
# ****************************************************
# Targets needed to bring the executable up to date
 
all: main.o
	$(CC) -o main main.cpp Domain.cpp Curvebase.cpp Horline.cpp Vertline.cpp Expline.cpp